Title: "Primer reporte en R Markdown"
Author: "José Arturo Reséndiz Lira"
output: html_document
========================================================

```{r Paquetes}
library(ggmap)
```

```{r GenerarDatos, message=FALSE}
clave.unica <- rep("000136989",3)
es.mixto <- c(universidad = 1, preparatoria = 1, secundaria = 1)
universidad <- geocode("ITAM")
preparatoria <- geocode("Escuela Cristobal Colon")
secundaria <- geocode("Instituto Ovalle Monday")

educacion <- rbind(universidad, preparatoria, secundaria)
educacion <- cbind(clave.unica, es.mixto, educacion)
```

```{r ObtenciónCoordenadasYMapas, warning=FALSE, message=FALSE}
limites <- make_bbox(lon, lat, educacion, f = 0.7)
mapa <- get_map(location = limites, 
                maptype = "roadmap", 
                source = "google")
```

```{r GraficarLocalizaciones, echo=FALSE}
ggmap(mapa) + 
geom_point(data = educacion, 
           aes(x = lon, y = lat), 
           size = 4, alpha = 0.6, colour = "red")
```